# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

 title: Technical blog for F123 Visual
 tagline: Technology that enables
 baseurl: 'f123.github.io'
 url: 'https://f123.github.io/'
markdown: kramdown
markdown_ext: "kd,kdwn,kdown,kramdown,md,mdwn,mdown,mk,markdown"
kramdown:
    #auto_ids: true
paginate: 5
paginate_path: '/blog/page:num/'

gems: [jekyll-paginate, jekyll-feed]

# Includes
include: ["_pages"]

exclude:
  - LICENSE
  - README.md


collections:

  workflows:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: page
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

